# Generated by Django 3.2.5 on 2021-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Gender', max_length=15),
        ),
    ]
